version: '3.3'
services:
#############################################      
#              SPARK CLUSTER                #
#############################################
  spark-master:
    image: apache/spark:3.3.0-hadoop3.3
    container_name: spark-master
    expose:
      - "7077"
    ports:
      - "8181:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./spark:/spark
  spark-worker-1:
    image: apache/spark:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8083:8083"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
#############################################
#               ZEPPELIN                    #
#############################################
  zeppelin:
    image: apache/zeppelin:0.10.1
    ports:
      - "8080:8080"
    volumes:
      - ./spark:/zeppelin/spark
      - ./notebooks:/zeppelin/notebook
    environment:
      - "MASTER=spark://spark-master:7077"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/zeppelin/spark"