version: '3.3'
services:

  spark-master:
    image: apache/spark
    container_name: spark-master
    expose:
      - "7077"
    ports:
      - "8181:8080"
      - "7077:7077"
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
    volumes:
      - ./spark:/opt/spark
      
      
  spark-worker-1:
    image: apache/spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
     volumes:
      - ./spark:/opt/spark
      
      
  zeppelin:
    image: apache/zeppelin:0.10.1
    ports:
      - "8080:8080"
    volumes:
      - ./opt/spark:/zeppelin/opt/spark
      - ./notebooks:/zeppelin/notebook
    environment:
      - "MASTER=spark://spark-master:7077"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/zeppelin/spark"
      - "JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk"